# Site-level redirects
[[redirects]]
  from = "/affiliate/xyz"
  to = "https://thelifehack.org/"
  status = 301
  force = true
 
[build]
  publish = "dist"
  command = "npm run build"
[build.processing.html]
  pretty_urls = false
[[headers]]
  for = "/_astro/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
